# Generated by Django 3.1.1 on 2020-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoModel',
            new_name='contactmodel',
        ),
    ]
