# Generated by Django 3.1.1 on 2020-10-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201031_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.TextField()),
                ('gravity', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
