# Generated by Django 3.1.1 on 2020-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_ticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
