# Generated by Django 3.1.4 on 2020-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ticketmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'ordering': ['id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='status',
            field=models.TextField(default='unread'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.TextField(default='open'),
        ),
    ]
