# Generated by Django 3.1.4 on 2020-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20201205_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
