# Generated by Django 3.2.3 on 2021-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210126_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
