# Generated by Django 3.2.3 on 2021-05-28 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_auto_20210527_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='user',
            new_name='technician',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='description',
            field=models.TextField(default='Fatura para clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
