# Generated by Django 3.2.3 on 2021-05-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210528_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfils'},
        ),
    ]
