# Generated by Django 3.2.3 on 2021-06-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0019_auto_20210608_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
